import type { ComponentType } from 'react'
import {
  Fence,
  Warehouse,
  HousePlus,
  Hammer,
  Wrench,
  Brush,
  Ruler,
  Logs,
  TreePine,
  Building,
  DoorOpen,
  Blinds,
  Rows3,
  Bolt,
  Paintbrush,
  Construction,
  Shovel,
  Axe,
  Slice,
  Scissors,
  House,
  Phone,
  MapPin,
  FileText,
  Sprout,
} from 'lucide-react'

export const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  'fence': Fence,
  'car-garage': Warehouse,
  'home-plus': HousePlus,
  'hammer': Hammer,
  'tool': Wrench,
  'brush': Brush,
  'ruler': Ruler,
  'wood': Logs,
  'tree': TreePine,
  'building': Building,
  'door': DoorOpen,
  'window': Blinds,
  'stairs': Rows3,
  'bolt': Bolt,
  'paint': Paintbrush,
  'crane': Construction,
  'shovel': Shovel,
  'axe': Axe,
  'wave-saw-tool': Slice,
  'cut': Scissors,
  'home': House,
  'phone': Phone,
  'map-pin': MapPin,
  'file-description': FileText,
  'garden-cart': Sprout,
}
