import type { ComponentType } from 'react'
import {
  IconFence,
  IconCarGarage,
  IconHomePlus,
  IconHammer,
  IconTool,
  IconBrush,
  IconRuler,
  IconWood,
  IconTree,
  IconBuilding,
  IconDoor,
  IconWindow,
  IconStairs,
  IconBolt,
  IconPaint,
  IconCrane,
  IconShovel,
  IconAxe,
  IconSaw,
  IconDrill,
  IconHome,
  IconPhone,
  IconMapPin,
  IconFileDescription,
  IconGardenCart,
} from '@tabler/icons-react'

export const iconMap: Record<string, ComponentType<{ className?: string }>> = {
  'fence': IconFence,
  'car-garage': IconCarGarage,
  'home-plus': IconHomePlus,
  'hammer': IconHammer,
  'tool': IconTool,
  'brush': IconBrush,
  'ruler': IconRuler,
  'wood': IconWood,
  'tree': IconTree,
  'building': IconBuilding,
  'door': IconDoor,
  'window': IconWindow,
  'stairs': IconStairs,
  'bolt': IconBolt,
  'paint': IconPaint,
  'crane': IconCrane,
  'shovel': IconShovel,
  'axe': IconAxe,
  'saw': IconSaw,
  'drill': IconDrill,
  'home': IconHome,
  'phone': IconPhone,
  'map-pin': IconMapPin,
  'file-description': IconFileDescription,
  'garden-cart': IconGardenCart,
}
