import type { SelectField } from 'payload'

export const iconOptions: SelectField['options'] = [
  { label: 'Fence', value: 'fence' },
  { label: 'Car Garage', value: 'car-garage' },
  { label: 'Home Plus', value: 'home-plus' },
  { label: 'Hammer', value: 'hammer' },
  { label: 'Tool', value: 'tool' },
  { label: 'Brush', value: 'brush' },
  { label: 'Ruler', value: 'ruler' },
  { label: 'Wood', value: 'wood' },
  { label: 'Tree', value: 'tree' },
  { label: 'Building', value: 'building' },
  { label: 'Door', value: 'door' },
  { label: 'Window', value: 'window' },
  { label: 'Stairs', value: 'stairs' },
  { label: 'Bolt', value: 'bolt' },
  { label: 'Paint', value: 'paint' },
  { label: 'Crane', value: 'crane' },
  { label: 'Shovel', value: 'shovel' },
  { label: 'Axe', value: 'axe' },
  { label: 'Saw', value: 'wave-saw-tool' },
  { label: 'Cut', value: 'cut' },
  { label: 'Home', value: 'home' },
  { label: 'Phone', value: 'phone' },
  { label: 'Map Pin', value: 'map-pin' },
  { label: 'File Description', value: 'file-description' },
  { label: 'Garden Cart', value: 'garden-cart' },
]
